# Generated by Django 6.0.1 on 2026-04-05 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('es_fijo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categorías de ingresos',
            },
        ),
        migrations.CreateModel(
            name='CategoríaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('es_fijo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categorías de gastos',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='successify.categoríagasto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='successify.categoriaingreso')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('cerrado', models.BooleanField(default=False)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meses',
                'unique_together': {('owner', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='IngresoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='successify.ingreso')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='successify.mes')),
            ],
            options={
                'unique_together': {('ingreso', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='GastoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='successify.gasto')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='successify.mes')),
            ],
            options={
                'unique_together': {('gasto', 'mes')},
            },
        ),
    ]
