# Generated by Django 6.0.1 on 2026-04-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastomes',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='codigo',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresomes',
            name='codigo',
            field=models.CharField(blank=True, default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mes',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
