# Generated by Django 6.0.1 on 2026-04-15 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0002_alter_gastomes_codigo_alter_ingreso_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastomes',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gastomes',
            name='gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='successify.gasto'),
        ),
    ]
