# Generated by Django 6.0.1 on 2026-05-02 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0003_gastomes_nombre_alter_gastomes_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresomes',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingresomes',
            name='ingreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='successify.ingreso'),
        ),
    ]
