# Generated by Django 6.0.1 on 2026-05-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0004_ingresomes_nombre_alter_ingresomes_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoríagasto',
            old_name='name',
            new_name='nombre',
        ),
    ]
