# Generated by Django 6.0.1 on 2026-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0005_rename_name_categoríagasto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastomes',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
