# Generated by Django 6.0.1 on 2026-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0006_gastomes_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresomes',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
