# Generated by Django 6.0.1 on 2026-05-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0007_ingresomes_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='name',
            new_name='nombre',
        ),
    ]
