# Generated by Django 6.0.1 on 2026-05-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0008_rename_name_gasto_nombre_rename_name_ingreso_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaingreso',
            old_name='name',
            new_name='nombre',
        ),
    ]
