# Generated by Django 6.0.1 on 2026-06-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successify', '0009_rename_name_categoriaingreso_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGastoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin registro', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gasto_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgastos', to='successify.gastomes')),
            ],
        ),
    ]
